version: '3.7'

services:

    jenkins:
      image: viartifacts-docker.jfrog.io/caritas-online-beratung/jenkins:latest
      container_name: jenkins
      restart: "no"
      volumes:
        - ./jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 8080:8080
